CREATE TABLESPACE CZCENMSS_FM_1 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_FM_1_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_1_02.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data01/CZCEDB/CZCENMSS_FM_1_03.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_1_04.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_FM_2 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_FM_2_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_2_02.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_FM_3 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_FM_3_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_3_02.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data01/CZCEDB/CZCENMSS_FM_3_03.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_3_04.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_FM_4 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_FM_4_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_4_02.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data01/CZCEDB/CZCENMSS_FM_4_03.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_FM_4_04.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_IND_TS01 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_TS01_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_TS01_02.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 512K
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_IND_TS02 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_TS02_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_TS02_02.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data01/CZCEDB/CZCENMSS_TS02_03.dbf' SIZE 1024M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_TS02_04.dbf' SIZE 1024M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 512K
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_SPLEX_1 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_SP_1_01.dbf' SIZE 1024M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_SP_1_02.dbf' SIZE 1024M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_WB_1 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_WB_1_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_WB_1_02.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCENMSS_WH_1 DATAFILE 
  '/data01/CZCEDB/CZCENMSS_WH_1_01.dbf' SIZE 2048M AUTOEXTEND OFF,
  '/data02/CZCEDB/CZCENMSS_WH_1_02.dbf' SIZE 2048M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCE_IND_TS01 DATAFILE 
  '/data02/CZCEDB/czce_ind_ts0101.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE 2000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE CZCE_SPLEX_TS01 DATAFILE 
  '/data01/CZCEDB/czce_splex_ts0101.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE 2000M,
  '/data02/CZCEDB/czce_splex_ts0102.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE 2000M,
  '/data01/CZCEDB/czce_splex_ts0103.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE 2000M,
  '/data02/CZCEDB/czce_splex_ts0104.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE 2000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

DROP USER CZCENMSS CASCADE;

CREATE USER CZCENMSS
  IDENTIFIED BY CZCENMSS
  DEFAULT TABLESPACE CZCENMSS_FM_1
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 4 Roles for CZCENMSS 
  GRANT CONNECT TO CZCENMSS;
  GRANT RESOURCE TO CZCENMSS;
  GRANT DBA TO CZCENMSS;
  GRANT SELECT_CATALOG_ROLE TO CZCENMSS;
  ALTER USER CZCENMSS DEFAULT ROLE ALL;
  -- 10 System Privileges for CZCENMSS 
  GRANT UPDATE ANY TABLE TO CZCENMSS;
  GRANT SELECT ANY TABLE TO CZCENMSS;
  GRANT ALTER ANY TABLE TO CZCENMSS;
  GRANT CREATE ANY TABLE TO CZCENMSS;
  GRANT CREATE SYNONYM TO CZCENMSS;
  GRANT UNLIMITED TABLESPACE TO CZCENMSS;
  GRANT CREATE VIEW TO CZCENMSS;
  GRANT INSERT ANY TABLE TO CZCENMSS;
  GRANT DELETE ANY TABLE TO CZCENMSS;
  GRANT DROP ANY TABLE TO CZCENMSS;
  -- 6 Tablespace Quotas for CZCENMSS 
  ALTER USER CZCENMSS QUOTA UNLIMITED ON CZCENMSS_FM_1;
  ALTER USER CZCENMSS QUOTA UNLIMITED ON CZCENMSS_FM_2;
  ALTER USER CZCENMSS QUOTA UNLIMITED ON CZCENMSS_WH_1;
  ALTER USER CZCENMSS QUOTA UNLIMITED ON CZCENMSS_IND_TS01;
  ALTER USER CZCENMSS QUOTA UNLIMITED ON CZCENMSS_WB_1;
  ALTER USER CZCENMSS QUOTA UNLIMITED ON CZCENMSS_FM_3;